quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/gestao_colchoes?useSSL=false&serverTimezone=UTC

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.hibernate-orm.database.version-check.enabled=false

# API documentation
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=broccosoaresravi@gmail.com
quarkus.mailer.password=eppk yxmr ueml jtbf
quarkus.mailer.from=broccosoaresravi@gmail.com
quarkus.mailer.mock=false

# CORS 
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# Rate limiting
quarkus.http.limits.max-connections=100

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=https://programa-de-gestao.com

# Opcional: tempo de expiração (8 horas)
smallrye.jwt.new-token.lifespan=28800

# 1. Libera o Swagger e a definição da API (OpenAPI)
quarkus.http.auth.permission.swagger.paths=/swagger-ui/*,/q/swagger-ui/*,/q/openapi/*,/openapi/*,/v3/api-docs/*
quarkus.http.auth.permission.swagger.policy=permit

# 2. Libera o endpoint de login (auth)
quarkus.http.auth.permission.public.paths=/auth/*
quarkus.http.auth.permission.public.policy=permit

# 3. Bloqueia TODO o resto (precisa estar logado). (Colocamos o path como /api/* para não dar conflito com os caminhos do Quarkus (/q/...)
quarkus.http.auth.permission.authenticated.paths=/produtos/*,/vendas/*,/materias-primas/*,/despesas/*,/lojistas/*,/cidades/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Faz o Swagger entender que deve usar Bearer Token
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=Authentication
quarkus.smallrye-openapi.security-scheme-description=Cole apenas o token JWT (sem a palavra Bearer)